2019-05-21 16:51:27.4453|ERROR|Big.Unicentro.Unipolla.DataAccess.Common.Diagnostics.ExceptionLogging|An error occurred while updating the entries. See the inner exception for details.
   en System.Data.Entity.Internal.InternalContext.SaveChanges()
   en System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   en System.Data.Entity.DbContext.SaveChanges()
   en Big.Unicentro.Unipolla.DataAccess.DAL.BetDAL.SaveBets(UNIPOLLA_BET bet) en C:\Users\Administrador\Desktop\Proyecto Copa America\Vigente\Big.Unicentro.Unipolla\Big.Unicentro.Unipolla.DataAccess\DAL\BetDAL.cs:línea 57
